### ISSUE TITLE
failing to run jay in windows cmd 

### ISSUE THREAD

**Issue by makaravind** [nikersify/jay#1]
I installed globally and when I run the cmd jay I got the following error on windows. 

....\system32>jay
...\jay-repl\dist\eval.js:75
    template.console = new console_1.Console(process.stdout, process.stdin);
                     ^

TypeError: Cannot set property console of #<Object> which has only a getter
    at Object.createEvaluator (C:\Users\ARME-HYD-01\AppData\Roaming\npm\node_modules\jay-repl\dist\eval.js:75:22)
    at main (C:\Users\ARME-HYD-01\AppData\Roaming\npm\node_modules\jay-repl\dist\cli.js:91:56)
    at Object.<anonymous> (C:\Users\ARME-HYD-01\AppData\Roaming\npm\node_modules\jay-repl\dist\cli.js:160:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)

**Comment by nikersify** [comment]
Hey, what version of node are you using?

**Comment by makaravind** [comment]
yup, I'm at 8.11.2. What is the minimum version ?

**Comment by nikersify** [comment]
10.x

**Comment by makaravind** [comment]
yup, it worked! Thanks @nikersify

**Comment by schfkt** [comment]
@nikersify FYI, you can specify the minimum supported version in package.json: https://docs.npmjs.com/files/package.json#engines

So npm wil fail installing it for the node versions below 10.x.

**Comment by nikersify** [comment]
@schfkt unfortunately that only displays a warning when `npm install`ing, thank you for the suggestion though.

closing via a36049bc651fdff12a96e8d42dec003fab2a833f
