### ISSUE TITLE
Requiring built-in modules throws an error

### ISSUE THREAD

**Issue by chrissantamaria** [nikersify/jay#14]
Not sure if I'm missing something here - requiring standard NPM modules works as expected (such as `const axios = require('axios')`) but any built-in module such as `fs` or `querystring` fails:

```
node v12.4.0 npm@6.9.0 jay-repl@0.2.1
Type `> jay.help()` in the prompt for more information.
> const fs = require('fs')
C:\Users\Chris\AppData\Local\Yarn\Data\global\node_modules\jay-repl\dist\moduler.js:158
            throw new Error(`\`${id}\` has an invalid \`package.json\` file`);
            ^

Error: `fs` has an invalid `package.json` file
    at C:\Users\Chris\AppData\Local\Yarn\Data\global\node_modules\jay-repl\dist\moduler.js:158:19
    at Left.getOrElseL (C:\Users\Chris\AppData\Local\Yarn\Data\global\node_modules\fp-ts\lib\Either.js:127:16)
    at decodePkg (C:\Users\Chris\AppData\Local\Yarn\Data\global\node_modules\jay-repl\dist\moduler.js:157:13)
    at _resolve (C:\Users\Chris\AppData\Local\Yarn\Data\global\node_modules\jay-repl\dist\moduler.js:180:21)
    at _require (C:\Users\Chris\AppData\Local\Yarn\Data\global\node_modules\jay-repl\dist\moduler.js:191:39)
    at evalmachine.<anonymous>:1:12
    at Script.runInContext (vm.js:134:20)
    at Object.<anonymous> (C:\Users\Chris\AppData\Local\Yarn\Data\global\node_modules\jay-repl\dist\eval.js:94:41)
    at Generator.next (<anonymous>)
    at C:\Users\Chris\AppData\Local\Yarn\Data\global\node_modules\jay-repl\dist\eval.js:7:71
>
```

I'm on Windows 10 and installed jay globally with Yarn.

**Comment by nikersify** [comment]
definitely shouldn't be happening, thanks.

fyi - just like in the vanilla node repl - all built-in modules are available by default, there's no need to `require` them.

**Comment by talentlessguy** [comment]
having the same issue

![image](https://user-images.githubusercontent.com/35937217/64925486-ce54c000-d7f9-11e9-9d4d-5591c84db2ec.png)
