### ISSUE TITLE
Error: Cannot find module 'fp-ts/lib/Either' (Linux, node 10)

### ISSUE THREAD

**Issue by tomsquest** [nikersify/jay#2]
Error: `Error: Cannot find module 'fp-ts/lib/Either'`

Stack: 
```
$ node -v                                
v10.16.0

$ npm i -g jay-repl     
/home/tom/.nvm/versions/node/v10.16.0/bin/jay -> /home/tom/.nvm/versions/node/v10.16.0/lib/node_modules/jay-repl/dist/cli.js
npm WARN io-ts@1.10.0 requires a peer of fp-ts@^1.0.0 || ^2.0.0-rc.6 but none is installed. You must install peer dependencies yourself.

+ jay-repl@0.1.2
added 169 packages from 362 contributors in 2.182s

$ jay
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'fp-ts/lib/Either'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/tom/.nvm/versions/node/v10.16.0/lib/node_modules/jay-repl/node_modules/io-ts/lib/index.js:27:16)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by tomsquest** [comment]
You're welcome!
